language: python
python:
  - 2.7
services:
  - docker
install:
  - docker build -t mock_kbase .
  - docker run -d -p 7044:7044 -p 7109:7109 -p 7058:7058 --name mock_kbase mock_kbase
script:
  - docker ps | grep -q mock_kbase
  - python setup.py test