language: python
python:
  - 2.7
services:
  - docker
install:
  - docker build -t mock_kbase .
  - docker run -d -p 7078:7078 --name mock_kbase mock_kbase
script:
  - docker ps | grep -q mock_kbase
  - head -c 1G < /dev/urandom > testfile
  - curl -X GET http://localhost:7078/node
  - curl -X POST -F "upload=@testfile" http://localhost:7078/node
  - curl -X GET http://localhost:7078/node
